# Build

FROM node:slim AS builder

WORKDIR /app

COPY app/package.json app/package-lock.json ./

COPY app .

RUN npm ci

RUN npm run build

# Prod

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]