version: '3.8'

services:
  frontend:
    container_name: frontend
    image: hoopaugi/homepage-frontend
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./frontend/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot:/var/www/certbot/:ro
      - letsencrypt:/etc/nginx/ssl/:ro
    restart: unless-stopped

volumes:
  certbot:
  letsencrypt: