version: '3.8'

services:
  frontend:
    container_name: frontend
    image: hoopaugi/homepage-frontend
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./frontend/nginx/nginx.staging.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot:/var/www/certbot/:ro
      - letsencrypt:/etc/nginx/ssl/:ro
    restart: unless-stopped
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - certbot:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --email ${LETSENCRYPT_EMAIL} -d ${LETSENCRYPT_DOMAIN} --agree-tos

volumes:
  certbot:
  letsencrypt: