version: "3.8"

services:
  backend:
    container_name: homepage-backend
    build: services/backend
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
    restart: unless-stopped
  traefik:
    container_name: homepage_traefik
    image: traefik:v3.0
    command:
      # Debugging
      - --log.level=DEBUG
      - --api.insecure=true
      - --api.dashboard=true
      # Entrypoints
      - --entrypoints.web.address=:80
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped